### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by hiimwilson** [clij/clij-docs#4]
Loving clij so far Robert! Any chance you might be able to add median and standard deviation intensity projections features? It's super helpful for large fluorescence time series images.

**Comment by haesleinhuepf** [comment]
Hi @hiimwilson ,

this is an awesome idea. I just implemented it in the experimental code repository. In order to test it, please download the [clij-advanced-filters.jar](https://github.com/clij/clij-advanced-filters/releases/tag/0.1.0) and put it in the `plugins` directory of your Fiji installation. You also find an example macro here:
https://github.com/clij/clij-advanced-filters/blob/master/src/main/macro/projections.ijm

![image](https://user-images.githubusercontent.com/12660498/59962480-25424600-94e6-11e9-881d-e984aa0f94e5.png)

Let me know if it works and it will find its way to the next major CLIJ release.

Thanks again for the suggestion!

Cheers,
Robert

**Comment by hiimwilson** [comment]
That was quick!!! Thanks!

I'm having a little trouble getting correct outputs from CLIJ. I've included a comparison of baked-in FIJI stack projections alongside the CLIJ results. The STD projections don't appear to line up at all. And for the median intensity projection, i get what looks like a memory error? This only appears to happen when the median intensity projection command from the plugin menu, and subsequently makes it so I cannot run anymore CLIJ commands until i restart FIJI. I've tried flipping around the 3rd dimension from time to color or z and I'm still getting the same errors. 

Test Image details, it's a 301 image .nd2 timeseries imported via bioformats. 1024x1024px, 16-bit images. I'm running this on a 4GB Quadro M2000. 

Sorry if that is unclear. Happy to elaborate more. 

![image](https://user-images.githubusercontent.com/10383579/60033604-8006a980-966e-11e9-9a61-b1b49ca2eaea.png)

**Comment by haesleinhuepf** [comment]
Hey @hiimwilson 

thanks for testing! The math behind the std-dev projection was just wrong. I just fixed it and uploaded a [0.2.0 pre-release](https://github.com/clij/clij-advanced-filters/releases/tag/0.2.0). Regarding the median projection: If I try with the T1-head image, it's just perfectly matching the ImageJ1-implementations result. Would you mind sharing your example image?

I also wrote two new macros allowing you to test and compare:
https://github.com/clij/clij-advanced-filters/blob/master/src/main/macro/medianZProjectionComparion.ijm
https://github.com/clij/clij-advanced-filters/blob/master/src/main/macro/standardDeviationZProjectionComparion.ijm

Please try again and let me know if it works.

And thanks again for the suggestion and testing!

Cheers,
Robert

**Comment by hiimwilson** [comment]
Looks like things line up great now running it from the plugin menu, both stdev and median! not sure what you changed on the median, but it seems to work now? see below: (histograms match up within less than 1 pixel grey value between 16 and 32bit images, as expected)

![image](https://user-images.githubusercontent.com/10383579/60199285-30a8b080-9809-11e9-943c-d352abc19b56.png)

The macros weren't initially pulling the images off the GPU and throwing errors for the comparison section. But after restarting FIJI it appears to work for both the T1 head sample images as well as substituting in my own nd2 files and 16bit tiff stacks. all appears to be good on my end now!

Thanks for all your help and hard work. 

-Wilson
