### ISSUE TITLE
Out-of-date link in api_intro.md

### ISSUE THREAD

**Issue by camlloyd** [clij/clij-docs#6]
Hello, just checking as I'm trying to find the most up-to-date examples on _CLIJ-ifying_ a plugin. 

See: `More examples can be found in the src/main/jython and src/main/java directories.`

Should [`src/main/java`](https://github.com/mpicbg-csbd/clij-docs/blob/master/src/main/java/) be pointing to [`src/main/java`](https://github.com/clij/clij-docs/blob/master/src/main/java/) following commit [`948f158`](https://github.com/clij/clij-docs/commit/948f158c9d4c3d5baaa30111d28e40f5486766eb#diff-dc21d2eddecc5285fb2dc05cea7dec01R77)? 

Thanks!

**Comment by haesleinhuepf** [comment]
Hey @camlloyd,

thanks for spotting and reporting this one! It should be fixed now https://github.com/clij/clij-docs/commit/b641c10298128ef487b9714a99f60c252a0d4e09

Furthermore, if you need any assistance in clijing your plugin, just let me know!

Thanks!
Cheers,
Robert

**Comment by camlloyd** [comment]
Thanks @haesleinhuepf,

I'm sure I will be asking on the forum!
