### ISSUE TITLE
Out of memory with CLIIJ plugin in Fiji

### ISSUE THREAD

**Issue by DaniK-BIP** [clij/clij-docs#7]
Hello,

Within Fiji i have discovered the feature of being able to adapt the available amount of memory, speeding up processes using the CPU a lot. However, when trying to use the CLIJ plugin in Fiji, it always says it has run out of memory, despite me adapting to any range from 300 MB to 16000 MB(my system has 16000 MB of RAM and 4000MB of GPU memory. I have adjusted my registry to adapt the timing of my Graphics card drivers as stated in the Troubleshooting section of the CLIJ website for Nvidia cards.

I have included my systeminfo for ease

Friendly greeting,
Dani
[Systeminfo.txt](https://github.com/clij/clij-docs/files/4546795/Systeminfo.txt)

**Comment by haesleinhuepf** [comment]
Hi @DaniK-BIP ,

glad to hear you like clij. The memory setting of Fiji has nothing to do with GPU memory btw. CLIJ can access the full memory anyway. If you for example run 10 GPU/clij operations on a 300 MB image, the memory may fill up to 3 GB - depending on which operations you use. I wrote a little tutorial on how to deal with memory for clij2: https://clij.github.io/clij2-docs/md/basics/

Maybe you can use `CLIJ2_reportMemory()` and `CLIJ2_release()` calls to resolve the problem. Otherwise, I need to know more details:
1. What is the exact error message you are receiving?
2. What workflow are you executing? 

Let me know if this helps

Cheers,
Robert

**Comment by DaniK-BIP** [comment]
Hello Robert,

Thank you for the feedback, i have found the problem.
My GPU has 4GB available and i tried making it work on a 8GB .tiff file, once using a 50 MB .tiff file, CLIJ performed as intended!
Is there a way of limiting the amount of GPU memory a CLIJ process can use at a time? Perhaps this allows processing of images larger than the GPU memory.

Cheers,
Dani

**Comment by haesleinhuepf** [comment]
Hey @DaniK-BIP,

unfortunately, CLIJ cannot push images to GPU memory which are larger than GPU memory. Actually, you need enough space in GPU memory to also host intermediate and result images. 

If you like, you can try to use tiling. Tiling is available in the experimental branch of CLIJ: CLIJx. It splits an image into tiles and process them individually on the GPU. There is an example macro doing this: https://github.com/clij/clijx/blob/master/src/main/macro/processTiles3D.ijm

![clij_pullpushtile](https://user-images.githubusercontent.com/12660498/80574064-702fc280-8a01-11ea-8500-56f1aa7df143.gif)

If you want to go one step further, you could distribute tasks between several GPUs. Therefore you need programming skills in Java or Jython:
https://github.com/clij/clij-docs/blob/master/src/main/jython/multi_GPU_demo.py

Let me know if this helps!

Cheers,
Robert

**Comment by DaniK-BIP** [comment]
Hello Robert,

Good to hear!
I have gotten the macro to work, however, i have not gotten it to work on my own data. How is this achieved or where can i learn this?

Cheers,
Dani

**Comment by haesleinhuepf** [comment]
Hey @DaniK-BIP,

you could attend the NEUBIAS Academy next week (May 6th):
http://eubias.org/NEUBIAS/training-schools/neubias-academy-home/

If you prefer written training: there are a lot of explanations and examples on the clij website:
https://clij.github.io

Furthermore, I'm just setting up the clij2 website which will come with notebook-like tutorials and step-by-step explanations:
https://clij.github.io/clij2-docs

And if you struggle, I'm happy to support you. Also consider posting questions on https://image.sc, the "official" support channel ;-)

Cheers,
Robert

**Comment by DaniK-BIP** [comment]
Thanks for the suggestions!
Im sure this has solved my problem, thank you!

Cheers, Dani
